name: fingerprint
description: Fingerprint puglin to generates a hash needed for banking transactions.
version: 0.0.1

repository: https://github.com/JhoanSe7/fingerprint.git

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.hexa.fingerprint
        pluginClass: FingerprintPlugin
      ios:
        pluginClass: FingerprintPlugin

